### ISSUE TITLE
Hi, how is it going?

### ISSUE THREAD

**Issue by banjaminlee** [Arcron-ArchLinux/100-Days-Of-Code#1]
Hi. @Arcron-ArchLinux 
How is your day?

**Comment by Arcron-ArchLinux** [comment]
hi there!

**Comment by banjaminlee** [comment]
Fine, thanks 
And you?

**Comment by Arcron-ArchLinux** [comment]
same I am fine just bored trying to upload my github website

**Comment by Arcron-ArchLinux** [comment]
it is damn hard

**Comment by Arcron-ArchLinux** [comment]
if you use flask with python with selenium

**Comment by banjaminlee** [comment]
I have am issue right now.

**Comment by Arcron-ArchLinux** [comment]
what issue?

**Comment by banjaminlee** [comment]
I am going to make money in Upwork.
But I have a problem with my account.
Can you help me?

**Comment by Arcron-ArchLinux** [comment]
Um... 
what is upwork what problem do you have?
And as I told you I am an 11 year old so I do not know anything.
But I'll see if I can help

**Comment by banjaminlee** [comment]
I need someone who can create Upwork account for me.
Then I can give him money for that.

**Comment by Arcron-ArchLinux** [comment]
Well I do not have an Upwork or any money and account and I never create accounts for others and I never take money

**Comment by banjaminlee** [comment]
You can get passive income ($150 per month) if you help me to create an account.

**Comment by Arcron-ArchLinux** [comment]
I said I do not have a money or bank account, and I do not want money!

**Comment by Arcron-ArchLinux** [comment]
I help people and right now it is my age to learn and not earn money and I live in India so dollars do not work here
Sorry I cannot help with this issue I am closing this.

**Comment by banjaminlee** [comment]
You can ask other people if they are interested in.

**Comment by Arcron-ArchLinux** [comment]
You can ask yourself bye
Good night

**Comment by Arcron-ArchLinux** [comment]
hope someone helps you @banjaminlee
